# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod "MagicalRecord"

target 'AddressBook' do

end

target 'AddressBookTests' do

end

target 'AddressBookUITests' do

end

